### ISSUE TITLE
[Panzer Dragoon] Distorted audio effects on stage 2

### ISSUE THREAD

**Issue by vanfanel** [MiSTer-devel/Saturn_MiSTer#190]
On stage 2, when sandworms emerge/submerge on the sand, the sound effect sounds heavily distorted and too high.

This is how it sounds on the Saturn core:

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/837585/9e974983-1f4c-4be2-95bc-088ab26ab7f9

This is how the sound effect is played on a real Saturn:

https://youtu.be/wRMnaXJt8SM?t=929

You can see how much softer and deeper the audio effect is on the Saturn.

**Comment by vanfanel** [comment]
To go directly to stage too, you can use the level select cheat:

Press Start on the title screen, then press Up, Up, Down, Down, Left, Right, Left, Right, X, Y, Z

**Comment by srg320** [comment]
> To go directly to stage too, you can use the level select cheat:
> 
> Press Start on the title screen, then press Up, Up, Down, Down, Left, Right, Left, Right, X, Y, Z

Thanks for the hint, it will save time because I can't even get past the first stage )

**Comment by real-amano** [comment]
@vanfanel is this fixed with the latest revision? `

**Comment by vanfanel** [comment]
No, it's still sounding bad.

**Comment by real-amano** [comment]
That's surprising to hear since srg mentioned it in the patchnotes and even Video Game Esoterica had it in their video today: https://youtu.be/5cUp3U4Y4kM?si=2eODxcTQsCWNQCgF

Is it at least a bit improved for you or completely the same? If it is the same, can you re-check if you actually use the current build from discord that includes the fix?

**Comment by vanfanel** [comment]
@real-amano It has improved slightly, but the sound of the swimming sand worms is still harsh, too loud and very different from how the game sounds on real hardware. Yes, I am using latest build from Discord.

I really hoped this was fixed after the latest commits, of course. Before those, I was visiting the code repository on a daily basis, waiting for that. But sadly it seems it's still broken.

With regard to VGE's video: his videos are always rushed (he makes money by following Youtube's algorithm with non-stopping and repetitive talking, often half informed) and he even shows "Bug!" as a game with perfect audio while at least one sound effect is broken on the same video, look at exactly 10:03:

https://youtu.be/5cUp3U4Y4kM?t=603

**Comment by srg320** [comment]
> With regard to VGE's video: his videos are always rushed (he makes money by following Youtube's algorithm with non-stopping and repetitive talking, often half informed) and he even shows "Bug!" as a game with perfect audio while at least one sound effect is broken on the same video, look at exactly 10:03:

If you know of other corrupted sounds in other games, please tell me about them. The more I know about such sounds, the faster and easier it will be to fix them.

**Comment by Kuba-J** [comment]
> With regard to VGE's video: his videos are always rushed (he makes money by following Youtube's algorithm with non-stopping and repetitive talking, often half informed) and he even shows "Bug!" as a game with perfect audio while at least one sound effect is broken on the same video, look at exactly 10:03:
> 
> https://youtu.be/5cUp3U4Y4kM?t=603

I wanted to draw attention to this under this video , but strangely my comments disappear.

**Comment by real-amano** [comment]
@vanfanel , srg tinkered with the sounds again. Possibly fixed this time.

**Comment by vanfanel** [comment]
This is fixed now, sound is now as in the original hardware!
Interpolation... yes, that makes sense, sound is now very soft and pleasant in the games. For example, some Nights sound effects are now "soft" as in the original hardware too. @srg320 Many thanks for all the work you put on this dream of a core :)
