### ISSUE TITLE
Street Fighter Zero 3 - music timing during the intro is incorrect

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#216]
When the intro plays, you’ll notice that the music cuts off prematurely at the end of the intro.  This is because the visuals are running faster than the music.  The music timing should match the intro’s visuals.  The timing is correct on original hardware.  You can compare this with the cps2 arcade intro on the mister as well.

**Comment by ZmaxAldrey** [comment]
Try this version that was made available in this post that was corrected.

https://github.com/MiSTer-devel/Saturn_MiSTer/issues/63

**Comment by gleek12** [comment]
Tried this build.  The issue is still present for me.

**Comment by Zet-sensei** [comment]
A retest with at leats core 2024-08-17 should be appreciated, as some part of the sounc chip have been redone and shall pass all unitary tests now.

**Comment by gleek12** [comment]
I tested the 8-17 build.  The intro timing is still incorrect.  Here is a youtube video showing what the intro timing should be:

**Comment by Zet-sensei** [comment]
Now that we are pretty confident about the SCSP after all the tests passed.

Let's do a retest.

And the intro timing is still incorrect, so must be something else to check about timings.

**Comment by Zet-sensei** [comment]
Fixed with commits https://github.com/MiSTer-devel/Saturn_MiSTer/commit/12fea3af12b193e372541b5d1dbf8cf0862044bf & https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d731ce3038305b3172b46ec19a1ed33c04476ed4

**Comment by gleek12** [comment]
This is confirmed fixed!  Thanks!
