### ISSUE TITLE
Pyon Pyon Kyaruru no Mahjong Biyori // Corruption In Intro

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#251]
![Screenshot 2024-09-21 00-16-55](https://github.com/user-attachments/assets/16894e69-0d8e-40cf-8e27-659416086a29)

In the intro to Pyon Pyon Kyaruru no Mahjong Biyori, there a brief moment where the graphics corrupt. This is easy to replicate; all you need to do is let the intro play out and it's guaranteed to show up.

Tested on both the 09/18/2024 single and dual RAM builds with 128MB 2.9 RAM modules.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d7aee5703a2ff8b9829ccb1f78726b04f6031864 on a Dual RAM system.

**Comment by InfernoHabanero** [comment]
Yeah I can confirm it's fixed on the dual RAM build. Single RAM build actually has _worse_ glitching though, so this is a two-steps-back-two-steps-forward solution.

I'm going to still keep this open, but with the clarification that this is still a problem with the single RAM build.

**Comment by srg320** [comment]
The intro is very dependent on the RAM-H access speed. In a single build, RAM-H (and 6 other core memories) is located in ddram, which has low latency. So it is impossible to make the intro work correctly in a single sdram build.

**Comment by Zet-sensei** [comment]
For future reference.
Doesn't change after a new test asked to another user with the Single RAM core version 2024-11-16 & the FAST timings option ON.

**Comment by srg320** [comment]
> For future reference. Doesn't change after a new test asked to another user with the Single RAM core version 2024-11-16 & the FAST timings option ON.

The option will be useful for slowdowns in some fighting games and Digital Dance Mix freeze. In other cases this option is useless or even dangerous. I do not recommended to use this option regularly.

**Comment by Kuba-J** [comment]
> The option will be useful for slowdowns in some fighting games and Digital Dance Mix freeze. In other cases this option is useless or even dangerous. I do not recommended to use this option regularly.

What are the risks of using this option?

**Comment by srg320** [comment]
> > The option will be useful for slowdowns in some fighting games and Digital Dance Mix freeze. In other cases this option is useless or even dangerous. I do not recommended to use this option regularly.
> 
> What are the risks of using this option?

Freezes, graphical glitches, etc. Simply put: if you have problems with a specific game with this option enabled, you should check with it disabled.

**Comment by real-amano** [comment]
Thanks a lot for the detailed answer!

**Comment by Thelypody** [comment]
The game intro appears to play correctly on a singe RAM MiSTer with original timings on, [using a nightly build from tdelage on MiSTer FPGA Forum.](https://misterfpga.org/viewtopic.php?p=105772#p105772)

<img width="320" height="240" alt="Image" src="https://github.com/user-attachments/assets/f6d02390-7ad1-4a2d-b934-d1444b58b3e1" />

MiSTer Main: 20260325
Saturn_Single_20260326.rbf

**Comment by srg320** [comment]
That's great, but unfortunately it's just a lucky coincidence.
